improve clang-formatting commit hook for linux

diff --git a/.githooks/pre-commit-linux b/.githooks/pre-commit-linux
--- a/.githooks/pre-commit-linux
+++ b/.githooks/pre-commit-linux
@@ -4,18 +4,28 @@
 #    2. cp .githooks/pre-commit-linux .git/hooks/pre-commit
 #    3. git config core.hooksPath .git/hooks
 # pre-requisite: Docker
+# pre-requisite: Bash 4
 # pre-requisite: Git 2.9+
 
 adb_path="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )"
 
 echo "ArangoDB directory: $adb_path"
-cd "$adb_path"
+pushd "$adb_path" > /dev/null
 
-# some .h files are currently misinterpreted as Objective-C files by clang-format
-# TODO: rename .h files to .hpp, and remove .h file ending from the grep here
-community_diff=$(git diff HEAD --diff-filter=ACMRT --name-only -- arangod/ client-tools/ lib/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$')
-if ! [[ -z "${community_diff// }" ]]; then
-  docker run --rm -u "$(id -u):$(id -g)" --mount type=bind,source="$adb_path",target=/usr/src/arangodb arangodb/clang-format:1.0 "$community_diff"
+changed_files_filename=".clang-format-$$.changed.tmp"
+# clean up after ourselves
+trap "rm -f $changed_files_filename" EXIT SIGINT SIGTERM SIGHUP
+
+# collect a file of file names of all modified files in $changed_files
+git diff --cached --diff-filter=ACMRT --name-only -- arangod/ lib/ client-tools/ tests/ | grep -e '\.ipp$' -e '\.tpp$' -e '\.cpp$' -e '\.hpp$' -e '\.cc$' -e '\.c$' -e '\.h$' > "$changed_files_filename"
+
+if [ -s "$changed_files_filename" ]; then
+  # hand-over a list of changed files from the local filesystem into a Docker container that contains a fixed
+  # version of clang-format and some small shell wrapper to iterate over the list of files
+  docker run --rm -u "$(id -u):$(id -g)" --mount type=bind,source="$adb_path",target=/usr/src/arangodb jsteemann/clang-format-docker:0.1 "$changed_files_filename"
 fi
+status=$?
 
-echo "(done)"
+popd > /dev/null
+
+exit $status
