Really take old version.

diff --git a/3rdParty/icu-legacy/icu64/runConfigureICU b/3rdParty/icu-legacy/icu64/runConfigureICU
--- a/3rdParty/icu-legacy/icu64/runConfigureICU
+++ b/3rdParty/icu-legacy/icu64/runConfigureICU
@@ -36,9 +36,8 @@ the runConfigureICU command:
 
 The following names can be supplied as the argument for platform:
 
-    AIX                 Use the IBM XL xlclang/xlclang compilers on AIX
+    AIX                 Use the IBM Visual Age xlc_r/xlC_r compilers on AIX
     AIX/GCC             Use the GNU gcc/g++ compilers on AIX
-    AIX/OpenXL          Use the IBM Open XL ibm-clang_r/ibm-clang++_r compilers on AIX
     Cygwin              Use the GNU gcc/g++ compilers on Cygwin
     Cygwin/MSVC         Use the Microsoft Visual C++ compiler on Cygwin
     Cygwin/MSVC2005     Use the Microsoft Visual C++ 2005 compiler on Cygwin
@@ -46,16 +45,15 @@ The following names can be supplied as the argument for platform:
     FreeBSD             Use the clang/clang++ or GNU gcc/g++ compilers on FreeBSD
     HP-UX/ACC           Use the HP ANSI C/Advanced C++ compilers on HP-UX 11
     IBMi                Use the iCC compilers on IBM i, i5/OS, OS/400
-    Linux               Use the default cc/c++ compilers on Linux
-    Linux/clang         Use the clang/clang++ compilers on Linux
+    Linux               Use the clang/clang++ or GNU gcc/g++ compilers on Linux
     Linux/gcc           Use the GNU gcc/g++ compilers on Linux
     Linux/ECC           Use the Intel ECC compiler on Linux
     Linux/ICC           Use the Intel ICC compiler on Linux
-    Linux/VA            Use the IBM XL compiler on Power PC Linux
+    Linux/VA            Use the IBM Visual Age compiler on Power PC Linux
     MacOSX              Use the default compilers on MacOS X (Darwin)
     MacOSX/GCC          Use the GNU gcc/g++ compilers on MacOSX (Darwin)
     MinGW               Use the GNU gcc/g++ compilers on MinGW
-    MSYS/MSVC           Use the Microsoft Visual C++ compiler on MSYS
+    MSYS/MSVC           Use the Microsoft Visual C++ computer on MSYS
     QNX                 Use the QNX QCC compiler on QNX/Neutrino
     Solaris             Use the Sun cc/CC compilers on Solaris
     Solaris/GCC         Use the GNU gcc/g++ compilers on Solaris
@@ -136,17 +134,17 @@ fi
 case $platform in
     AIX)
         THE_OS=AIX
-        THE_COMP="xlclang"
-        CC=`which xlclang`; export CC
+        THE_COMP="xlC_r"
+        CC=`which xlc_r`; export CC
         if [ ! -x $CC ]; then
-           echo "ERROR: xlclang was not found, please check the PATH to make sure it is correct."; exit 1
+           echo "ERROR: xlc_r was not found, please check the PATH to make sure it is correct."; exit 1
         fi
-        CXX=`which xlclang++`; export CXX
+        CXX=`which xlC_r`; export CXX
         if [ ! -x $CXX ]; then
-           echo "ERROR: xlclang++ was not found, please check the PATH to make sure it is correct."; exit 1
+           echo "ERROR: xlC_r was not found, please check the PATH to make sure it is correct."; exit 1
         fi
-        RELEASE_CFLAGS="-O3 -qstrict=ieeefp"
-        RELEASE_CXXFLAGS="-O3 -qstrict=ieeefp"
+        RELEASE_CFLAGS="-O2 -qmaxmem=-1"
+        RELEASE_CXXFLAGS="-O2 -qmaxmem=-1"
         ;;
     AIX/GCC)
         THE_OS=AIX
@@ -156,20 +154,6 @@ case $platform in
         DEBUG_CFLAGS='-g -O0'
         DEBUG_CXXFLAGS='-g -O0'
         ;;
-    AIX/OpenXL)
-        THE_OS=AIX
-        THE_COMP="ibm-clang_r"
-        CC=`which ibm-clang_r`; export CC
-        if [ ! -x $CC ]; then
-           echo "ERROR: ibm-clang_r was not found, please check the PATH to make sure it is correct."; exit 1
-        fi
-        CXX=`which ibm-clang++_r`; export CXX
-        if [ ! -x $CXX ]; then
-           echo "ERROR: ibm-clang++_r was not found, please check the PATH to make sure it is correct."; exit 1
-        fi
-        RELEASE_CFLAGS="-O3"
-        RELEASE_CXXFLAGS="-O3"
-	;;
     Solaris)
         THE_OS=SOLARIS
         THE_COMP="Sun's CC"
@@ -244,11 +228,11 @@ case $platform in
         ;;
     Linux/VA)
         THE_OS="Linux"
-        THE_COMP="IBM XL C++ Compiler"
-        CC=`which xlclang`; export CC
-        CXX=`which xlclang++`; export CXX
-        RELEASE_CFLAGS="-O3"
-        RELEASE_CXXFLAGS="-O3"
+        THE_COMP="IBM Visual Age C++ Compiler"
+        CC=`which xlc_r`; export CC
+        CXX=`which xlC_r`; export CXX
+        RELEASE_CFLAGS="-O2 -qmaxmem=-1"
+        RELEASE_CXXFLAGS="-O2 -qmaxmem=-1"
         ;;
     Linux/gcc)
         THE_OS="Linux"
@@ -260,19 +244,9 @@ case $platform in
         DEBUG_CFLAGS='-g'
         DEBUG_CXXFLAGS='-g'
         ;;
-    Linux/clang)
-        THE_OS="Linux"
-        THE_COMP="the Clang C++"
-        CC=clang; export CC
-        CXX=clang++; export CXX
-        RELEASE_CFLAGS='-O3'
-        RELEASE_CXXFLAGS='-O3'
-        DEBUG_CFLAGS='-g'
-        DEBUG_CXXFLAGS='-g'
-        ;;
     Linux*)
         THE_OS="Linux"
-        THE_COMP="the default C++"
+        THE_COMP="the clang or else GNU C++"
         RELEASE_CFLAGS='-O3'
         RELEASE_CXXFLAGS='-O3'
         DEBUG_CFLAGS='-g'
diff --git a/3rdParty/icu-legacy/icu64/test/hdrtst/Makefile.in b/3rdParty/icu-legacy/icu64/test/hdrtst/Makefile.in
--- a/3rdParty/icu-legacy/icu64/test/hdrtst/Makefile.in
+++ b/3rdParty/icu-legacy/icu64/test/hdrtst/Makefile.in
@@ -16,16 +16,10 @@
 ##  unicode/ucnv.h -	0
 ##
 ##    .. etc.  Anything other than zero is an error. (except for the deprecation tests, where '1' is the correct value)
+##              
 ##
-##  If the header test is run for a particular UCONFIG_NO_XXX=1 variation (see uconfig.h)
-##  then invoke the test with 'make UCONFIG_NO="-DUCONFIG_NO_XXX=1 check'.
-##  For standard header test run the UCONFIG_NO variable will evaluate to empty string.
-##
-##  If a header fails the C compile test it is likely because the header is a
-##  C++ header and it isn't properly guarded by the U_SHOW_CPLUSPLUS_API macro.
-##
-##  If a header fails the cppguardtest test it is likely because the header doesn't
-##  include the utypes.h header first *before* using the macro U_SHOW_CPLUSPLUS_API.
+##  If a header fails the C compile because it's a C++ header, add it to the
+##  file named 'cxxfiles.txt' in this directory.
 ##
 ##  If a header fails because it is deprecated, add it to the 'dfiles.txt'
 ##
@@ -39,102 +33,135 @@ top_builddir = ../..
 subdir = test/hdrtst
 
 include $(shell icu-config --incfile)
+DIRS=$(prefix)/include/unicode
+LDIRS=$(prefix)/include/layout
+ECHO_T=@ECHO_T@
+ECHO_C=@ECHO_C@
+ECHO_N=@ECHO_N@
 
 all: 
 	@echo Please read this Makefile for more information.
 	@echo run \'$(MAKE) check\' to run the test "(use -k if you don't want to stop on errs)"
 
-check: dtest ctest cpptest drafttest deprtest internaltest obsoletetest cppguardtest
+E_NUM=8
+E_D="[1/$(E_NUM)] Deprecated: "
+E_C="[2/$(E_NUM)] C  : "
+E_CXX="[3/$(E_NUM)] C++: "
+E_CXX_L="[4/$(E_NUM)] C++ layout: "
+E_DRF="[5/$(E_NUM)] Hide Draft: "
+E_DEP="[6/$(E_NUM)] Hide Deprecated: "
+E_INT="[7/$(E_NUM)] Hide Internal: "
+E_OBS="[8/$(E_NUM)] Hide Obsolete: "
 
-headertest:
-	@FAIL=0;stub=ht_stub_$(NAME.headers).$(SUFFIX.headers); for file in "$(prefix)/include/unicode"/*.h ; do \
-		incfile=`basename $$file` ; \
-		echo "$(NAME.headers) unicode/$$incfile" ; \
-		echo "#include <unicode/$$incfile>" > $$stub ; \
-		echo 'void junk(){}' >> $$stub ; \
-		$(COMPILE.headers) $(cppflags) $(FLAGS.headers) $(UCONFIG_NO) $$stub || FAIL=1 ; \
-		rm -f $$stub; \
-	done ; \
-	exit $$FAIL
+check: dtest ctest cpptest doclean drafttest deprtest internaltest obsoletetest
+ifeq ($(MAKECMDGOALS),check)
+	$(MAKE) clean
+else
+	@echo "(not cleaning automatically)"
+endif
 
-ctest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.c)" \
-		SUFFIX.headers=c \
-		FLAGS.headers=
+# break dependency
+doclean:
+	make clean
 
 cpptest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.cc)" \
-		SUFFIX.headers=cpp \
-		FLAGS.headers=
+	@FAIL=0;for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/pfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> ht_$$incfile.cpp ; \
+          $(COMPILE.cc) -c $(cppflags) ht_$$incfile.cpp || FAIL=1 ; \
+	done ;\
+	exit $$FAIL
 
-drafttest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.cc)" \
-		SUFFIX.headers=cpp \
-		FLAGS.headers="-DU_HIDE_DRAFT_API"
-
-deprtest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.cc)" \
-		SUFFIX.headers=cpp \
-		FLAGS.headers="-DU_HIDE_DEPRECATED_API"
-
-internaltest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.cc)" \
-		SUFFIX.headers=cpp \
-		FLAGS.headers="-DU_HIDE_INTERNAL_API"
-
-obsoletetest:
-	$(MAKE) headertest \
-		NAME.headers=$@ \
-		COMPILE.headers="$(COMPILE.cc)" \
-		SUFFIX.headers=cpp \
-		FLAGS.headers="-DU_HIDE_OBSOLETE_API"
+# layout is removed
 
 dtest:
-	@FAIL=0;NONE="(No deprecated headers)";stub=ht_stub_dtest.cpp;for incfile in `cat $(srcdir)/dfiles.txt | grep -v '^#' | sort` ; do \
-		NONE= ; \
-		echo "$@ unicode/$$incfile" ; \
-		echo "#include <unicode/$$incfile>" > $$stub ; \
-		echo 'void junk(){}' >> $$stub ; \
-		$(COMPILE.cc) $(cppflags) $$stub 2>&1 | tee $$stub.out || FAIL=1 ; \
-		if ! cat $$stub.out | sed -e 's/^.*#error[^"]*"//' | grep -v ht_ | grep -v "$$incfile header is obsolete"; then \
-			echo "** FAIL Header unicode/$$incfile is not obsoleted properly" ; \
-			FAIL=1 ; \
-		fi ; \
-		rm -f $$stub*; \
+	@FAIL=0;NONE="(No deprecated headers)";for stub in `cat $(srcdir)/dfiles.txt | grep -v '^#'` ; do \
+	  file=unicode/$$stub ; \
+	  NONE="" ; \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> ht_$$incfile.cpp ; \
+	  echo > ht_dep.junk ; \
+          $(COMPILE.cc) -c $(cppflags) ht_$$incfile.cpp 2>&1 | sed -e 's/^.*#error[^"]*"//' | fgrep -v ht_ | tee ht_dep.junk | fgrep -v "$$incfile.h header is obsolete" ; \
+	  RES=$$? ; \
+	  echo $$RES ; \
+	  fgrep -q "$$incfile.h header is obsolete" ht_dep.junk || echo "** FAIL Header unicode/$$incfile.h is not obsoleted properly" ; \
+	  fgrep -q "$$incfile.h header is obsolete" ht_dep.junk || FAIL=1 ; \
+	  rm -f unicode/$$stub ; \
 	done ; \
 	echo "$@: $$NONE - exit status $$FAIL" ; \
 	exit $$FAIL
 
-cppguardtest:
-	@FAIL=0;stub=ht_stub_cppguardtest.cpp; for file in "$(prefix)/include/unicode"/*.h ; do \
-		incfile=`basename $$file` ; \
-		if grep -q "U_SHOW_CPLUSPLUS_API" $$file ; then \
-			echo "$@ unicode/$$incfile" ; \
-			echo "#include <unicode/$$incfile>" > $$stub ; \
-			echo 'void junk(){}' >> $$stub ; \
-			echo '#if !defined(U_SHOW_CPLUSPLUS_API)' >> $$stub ; \
-			echo "#error The header '$$incfile' refers to the macro U_SHOW_CPLUSPLUS_API (defined in utypes.h) but either does not include utypes.h or does so incorrectly." >> $$stub ; \
-			echo '#endif' >> $$stub ; \
-			$(COMPILE.cc) $(cppflags) $(UCONFIG_NO) $$stub || FAIL=1 ; \
-			rm -f $$stub; \
-		else \
-			echo "$@ skipping unicode/$$incfile" ; \
-		fi ; \
+#  < ht_dep.junk &&  ; \
+
+
+ctest:
+	@echo Building test harness for header files in ../../common and ../../i18n
+	@FAIL=0;for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/cxxfiles.txt | tee cfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#include "'unicode/$$incfile'.h"' > ht_$$incfile.c ; \
+	  echo 'void junk(void);' >> ht_$$incfile.c ; \
+	  echo 'void junk(){}' >> ht_$$incfile.c ; \
+          $(COMPILE.c) -c $(cppflags) ht_$$incfile.c || FAIL=1 ; \
+	done ;\
+	exit $$FAIL
+
+drafttest:
+	@FAIL=0;for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/pfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#define U_HIDE_DRAFT_API' > hd_$$incfile.cpp ; \
+	  echo '#include "'unicode/$$incfile'.h"' >> hd_$$incfile.cpp ; \
+	  echo 'void junk(void);' >> hd_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> hd_$$incfile.cpp ; \
+          $(COMPILE.cc) -c $(cppflags) hd_$$incfile.cpp ||FAIL=1 ; \
+	done ;\
+	exit $$FAIL
+
+deprtest:
+	@FAIL=0; for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/pfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#define U_HIDE_DEPRECATED_API' > hdp_$$incfile.cpp ; \
+	  echo '#include "'unicode/$$incfile'.h"' >> hdp_$$incfile.cpp ; \
+	  echo 'void junk(void);' >> hdp_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> hdp_$$incfile.cpp ; \
+          $(COMPILE.cc) -c $(cppflags) hdp_$$incfile.cpp || FAIL=1; \
+	done ; \
+	exit $$FAIL
+
+internaltest:
+	@FAIL=0;\
+	 for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/pfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#define U_HIDE_INTERNAL_API' > hin_$$incfile.cpp ; \
+	  echo '#include "'unicode/$$incfile'.h"' >> hin_$$incfile.cpp ; \
+	  echo 'void junk(void);' >> hin_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> hin_$$incfile.cpp ; \
+          $(COMPILE.cc) -c $(cppflags) hin_$$incfile.cpp || FAIL=1 ; \
+	done ; \
+	exit $$FAIL
+
+obsoletetest:
+	@FAIL=0;for file in `ls $(prefix)/include/unicode/*.h | fgrep -v -f $(srcdir)/pfiles.txt`; do \
+	  incfile=`basename $$file .h` ; \
+	  echo "$@ unicode/$$incfile.h" ; \
+	  echo '#define U_HIDE_OBSOLETE_API' > hob_$$incfile.cpp ; \
+	  echo '#include "'unicode/$$incfile'.h"' >> hob_$$incfile.cpp ; \
+	  echo 'void junk(void);' >> hob_$$incfile.cpp ; \
+	  echo 'void junk(){}' >> hob_$$incfile.cpp ; \
+          $(COMPILE.cc) -c $(cppflags) hob_$$incfile.cpp || FAIL=1 ; \
 	done ; \
 	exit $$FAIL
 
 clean:
-	-@rm -f ht_*
+	-@echo cleaning..
+	-@rm -f *.h *.c *.cpp *.o *.junk cfiles.txt
 
 distclean: clean
 	-@rm -f Makefile
@@ -143,4 +170,5 @@ Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) \
 	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
-.PHONY:	doclean check all headertest cpptest dtest cppguardtest ctest clean distclean
+.PHONY:	doclean check all cpptest dtest ctest clean distclean
+
