Fail setup instead of using a separate job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,18 @@ jobs:
         type: string
         default: "devel"
     steps:
+      - when:
+          condition:
+            not:
+              or:
+                - equal: [devel, << pipeline.git.branch >>]
+                - equal: [api, << pipeline.trigger_source >>]
+                - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
+          steps:
+            - run: |
+                echo "Intentional build failure - to run an actual build please trigger a pipeline manually."
+                exit 1
+
       - run:
           name: Checkout
           command: |
@@ -43,34 +55,9 @@ jobs:
           configuration_path: generated_config.yml # use newly generated config to continue
           parameters: '{"default-enterprise-branch": "<< parameters.default-enterprise-branch >>"}'
 
-  fail:
-    docker:
-      - image: cimg/base:current
-    resource_class: small
-    steps:
-      - run:
-          name: Fail
-          command: |
-            echo "Intentional build failure - to run an actual build please trigger a pipeline manually."
-            exit 1
-
 # our single workflow, that triggers the setup job defined above
 workflows:
   setup:
-    when:
-      or:
-        - equal: [devel, << pipeline.git.branch >>]
-        - equal: [api, << pipeline.trigger_source >>]
-        - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
     jobs:
       - generate-config:
           definitions: "tests/test-definitions.txt"
-  fail-build:
-    when:
-      not:
-        or:
-          - equal: [devel, << pipeline.git.branch >>]
-          - equal: [api, << pipeline.trigger_source >>]
-          - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
-    jobs:
-      - fail
