ensure the 'unittests' script properly finds 'arangosh' and the build directory

diff --git a/scripts/unittest b/scripts/unittest
--- a/scripts/unittest
+++ b/scripts/unittest
@@ -27,16 +27,33 @@ if [ -z "${ARANGOSH}" ];  then
     elif [ -x usr/bin/arangosh ];  then
         ARANGOSH=usr/bin/arangosh
     else
-        echo "$0: cannot locate arangosh"
-        exit 1
+        ARANGOSH="$(find . -name arangosh -executable -type f | head -n 1)"
+        [ -x "${ARANGOSH}" ] || {
+          echo "$0: cannot locate arangosh"
+          exit 1
+        }
     fi
 fi
 
+EXEC_PATH="$(dirname "$(dirname "$(readlink -m "$0")")")"
+declare -a EXTRA_ARGS
+
+[ -x "${ARANGOSH}" ] && ARANGOSH="$(readlink -m "${ARANGOSH}")"
+
+[[ " $@ " =~ "--build" ]] || {
+  BUILD_PATH="$(dirname "$(dirname "${ARANGOSH}")")"
+  BUILD_PATH="${BUILD_PATH#${EXEC_PATH}/}"
+  EXTRA_ARGS=("--build" "${BUILD_PATH}")
+}
+
 #
+(
+cd "${EXEC_PATH}"
 exec $NUMA $ARANGOSH \
      -c etc${PS}relative${PS}arangosh.conf \
      --log.level warning \
      --server.endpoint tcp://127.0.0.1:${PORT} \
      --javascript.execute UnitTests${PS}unittest.js \
      -- \
-     "$@"
+     "$@" "${EXTRA_ARGS[@]}"
+)
