Upgrade ETCD to new upstream version 2.2.2

diff --git a/3rdParty/etcd/scripts/build-aci b/3rdParty/etcd/scripts/build-aci
--- a/3rdParty/etcd/scripts/build-aci
+++ b/3rdParty/etcd/scripts/build-aci
@@ -1,20 +1,23 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+BINARYDIR=${BINARYDIR:-bin}
+BUILDDIR=${BUILDDIR:-bin}
 
 # A non-installed actool can be used, for example:
 # ACTOOL=../../appc/spec/bin/actool
 ACTOOL=${ACTOOL:-actool}
 
-IMAGEDIR=${IMAGEDIR:-bin/image-aci}
+IMAGEDIR=${IMAGEDIR:-$BUILDDIR/image-aci}
 
 VERSION=$1
 
-if [ ! -x "$ACTOOL" ] ; then
+if ! command -v $ACTOOL >/dev/null; then
     echo "actool ($ACTOOL) is not executable"
     exit 1
 fi
 
-if [ ! -x bin/etcd ] ; then
-    echo "bin/etcd not found. Is it compiled?"
+if [ ! -x $BINARYDIR/etcd ] ; then
+    echo "$BINARYDIR/etcd not found. Is it compiled?"
     exit 1
 fi
 
@@ -34,14 +37,14 @@ if [ -n "$(ls -A $IMAGEDIR/rootfs)" ]; then
     exit 1
 fi
 
-cp bin/etcd bin/etcdctl $IMAGEDIR/rootfs/
+cp $BINARYDIR/etcd $BINARYDIR/etcdctl $IMAGEDIR/rootfs/
 cp README.md            $IMAGEDIR/rootfs/
 cp etcdctl/README.md    $IMAGEDIR/rootfs/README-etcdctl.md
 cp -r Documentation     $IMAGEDIR/rootfs/
 
 cat <<DF > $IMAGEDIR/manifest
 {
-    "acVersion": "0.1.1",
+    "acVersion": "0.5.1",
     "acKind": "ImageManifest",
     "name": "coreos.com/etcd",
     "labels": [
@@ -50,11 +53,45 @@ cat <<DF > $IMAGEDIR/manifest
         {"name": "version", "value": "${VERSION}"}
     ],
     "app": {
+        "environment": [
+             {
+                    "name": "ETCD_DATA_DIR",
+                    "value": "/data-dir"
+             }
+        ],
         "exec": [
              "/etcd"
         ],
         "user": "0",
-        "group": "0"
+        "group": "0",
+        "mountPoints": [
+             {
+                    "name": "data-dir",
+                    "path": "/data-dir"
+             }
+        ],
+        "ports": [
+            {
+                "name": "legacy-client",
+                "port": 4001,
+                "protocol": "tcp"
+            },
+            {
+                "name": "client",
+                "port": 2379,
+                "protocol": "tcp"
+            },
+            {
+                "name": "legacy-peer",
+                "port": 7001,
+                "protocol": "tcp"
+            },
+            {
+                "name": "peer",
+                "port": 2380,
+                "protocol": "tcp"
+            }
+        ]
     }
 }
 DF
@@ -64,4 +101,4 @@ cat <<DF > $IMAGEDIR/rootfs/etc/hosts
 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
 DF
 
-$ACTOOL build -overwrite=true $IMAGEDIR bin/etcd-${1}-linux-amd64.aci
+$ACTOOL build -overwrite=true $IMAGEDIR $BUILDDIR/etcd-${1}-linux-amd64.aci
